export interface AreaOption {
  area: string;
  city: string;
  ward: string;
}

export const LOCATIONS: AreaOption[] = [
  // Delhi - Central
  { area: 'Connaught Place', city: 'Delhi', ward: 'Central Delhi Ward 1' },
  { area: 'Paharganj', city: 'Delhi', ward: 'Central Delhi Ward 2' },
  { area: 'Karol Bagh', city: 'Delhi', ward: 'Central Delhi Ward 3' },
  { area: 'Chandni Chowk', city: 'Delhi', ward: 'Central Delhi Ward 4' },
  { area: 'Civil Lines', city: 'Delhi', ward: 'North Delhi Ward 1' },
  { area: 'Model Town', city: 'Delhi', ward: 'North Delhi Ward 2' },
  { area: 'Subhash Nagar', city: 'Delhi', ward: 'North Delhi Ward 3' },
  // Delhi - South
  { area: 'Lajpat Nagar', city: 'Delhi', ward: 'South Delhi Ward 1' },
  { area: 'Greater Kailash I', city: 'Delhi', ward: 'South Delhi Ward 2' },
  { area: 'Greater Kailash II', city: 'Delhi', ward: 'South Delhi Ward 3' },
  { area: 'Hauz Khas', city: 'Delhi', ward: 'South Delhi Ward 4' },
  { area: 'Malviya Nagar', city: 'Delhi', ward: 'South Delhi Ward 5' },
  { area: 'Saket', city: 'Delhi', ward: 'South Delhi Ward 6' },
  { area: 'Vasant Kunj', city: 'Delhi', ward: 'South Delhi Ward 7' },
  { area: 'Vasant Vihar', city: 'Delhi', ward: 'South Delhi Ward 8' },
  { area: 'South Extension', city: 'Delhi', ward: 'South Delhi Ward 9' },
  { area: 'Nehru Place', city: 'Delhi', ward: 'South Delhi Ward 10' },
  // Delhi - West
  { area: 'Dwarka Sector 6', city: 'Delhi', ward: 'West Delhi Ward 1' },
  { area: 'Dwarka Sector 12', city: 'Delhi', ward: 'West Delhi Ward 2' },
  { area: 'Dwarka Sector 23', city: 'Delhi', ward: 'West Delhi Ward 3' },
  { area: 'Janakpuri', city: 'Delhi', ward: 'West Delhi Ward 4' },
  { area: 'Rajouri Garden', city: 'Delhi', ward: 'West Delhi Ward 5' },
  { area: 'Paschim Vihar', city: 'Delhi', ward: 'West Delhi Ward 6' },
  { area: 'Uttam Nagar', city: 'Delhi', ward: 'West Delhi Ward 7' },
  // Delhi - North-West
  { area: 'Rohini Sector 3', city: 'Delhi', ward: 'North West Delhi Ward 1' },
  { area: 'Rohini Sector 11', city: 'Delhi', ward: 'North West Delhi Ward 2' },
  { area: 'Pitampura', city: 'Delhi', ward: 'North West Delhi Ward 3' },
  { area: 'Shalimar Bagh', city: 'Delhi', ward: 'North West Delhi Ward 4' },
  { area: 'Ashok Vihar', city: 'Delhi', ward: 'North West Delhi Ward 5' },
  { area: 'Rani Bagh', city: 'Delhi', ward: 'North West Delhi Ward 6' },
  // Delhi - East
  { area: 'Shahdara', city: 'Delhi', ward: 'East Delhi Ward 1' },
  { area: 'Preet Vihar', city: 'Delhi', ward: 'East Delhi Ward 2' },
  { area: 'Mayur Vihar Phase 1', city: 'Delhi', ward: 'East Delhi Ward 3' },
  { area: 'Dilshad Garden', city: 'Delhi', ward: 'East Delhi Ward 4' },
  { area: 'Vivek Vihar', city: 'Delhi', ward: 'East Delhi Ward 5' },
  { area: 'Patparganj', city: 'Delhi', ward: 'East Delhi Ward 6' },
  { area: 'IP Extension', city: 'Delhi', ward: 'East Delhi Ward 7' },
  // Ghaziabad
  { area: 'Indirapuram', city: 'Ghaziabad', ward: 'Ghaziabad Ward 1' },
  { area: 'Vaishali Sector 1', city: 'Ghaziabad', ward: 'Ghaziabad Ward 2' },
  { area: 'Vaishali Sector 4', city: 'Ghaziabad', ward: 'Ghaziabad Ward 3' },
  { area: 'Kaushambi', city: 'Ghaziabad', ward: 'Ghaziabad Ward 4' },
  { area: 'Raj Nagar Extension', city: 'Ghaziabad', ward: 'Ghaziabad Ward 5' },
  { area: 'Raj Nagar', city: 'Ghaziabad', ward: 'Ghaziabad Ward 6' },
  { area: 'Sahibabad', city: 'Ghaziabad', ward: 'Ghaziabad Ward 7' },
  { area: 'Mohan Nagar', city: 'Ghaziabad', ward: 'Ghaziabad Ward 8' },
  { area: 'Vijay Nagar', city: 'Ghaziabad', ward: 'Ghaziabad Ward 9' },
  { area: 'Abhay Khand', city: 'Ghaziabad', ward: 'Ghaziabad Ward 10' },
  { area: 'Nyay Khand', city: 'Ghaziabad', ward: 'Ghaziabad Ward 11' },
  { area: 'Vasundhara Sector 1', city: 'Ghaziabad', ward: 'Ghaziabad Ward 12' },
  { area: 'Vasundhara Sector 4', city: 'Ghaziabad', ward: 'Ghaziabad Ward 13' },
  { area: 'Crossings Republik', city: 'Ghaziabad', ward: 'Ghaziabad Ward 14' },
  { area: 'Siddharth Vihar', city: 'Ghaziabad', ward: 'Ghaziabad Ward 15' },
  { area: 'Govindpuram', city: 'Ghaziabad', ward: 'Ghaziabad Ward 16' },
  { area: 'Pratap Vihar', city: 'Ghaziabad', ward: 'Ghaziabad Ward 17' },
  { area: 'Surya Nagar', city: 'Ghaziabad', ward: 'Ghaziabad Ward 18' },
  { area: 'Lal Kuan', city: 'Ghaziabad', ward: 'Ghaziabad Ward 19' },
  { area: 'Nandgram', city: 'Ghaziabad', ward: 'Ghaziabad Ward 20' },
  { area: 'Rajendra Nagar', city: 'Ghaziabad', ward: 'Ghaziabad Ward 21' },
  { area: 'Shastri Nagar', city: 'Ghaziabad', ward: 'Ghaziabad Ward 22' },
  { area: 'Gandhi Nagar', city: 'Ghaziabad', ward: 'Ghaziabad Ward 23' },
  // Noida - Sectors
  { area: 'Sector 1', city: 'Noida', ward: 'Noida Ward 1' },
  { area: 'Sector 2', city: 'Noida', ward: 'Noida Ward 1' },
  { area: 'Sector 3', city: 'Noida', ward: 'Noida Ward 1' },
  { area: 'Sector 4', city: 'Noida', ward: 'Noida Ward 1' },
  { area: 'Sector 5', city: 'Noida', ward: 'Noida Ward 2' },
  { area: 'Sector 6', city: 'Noida', ward: 'Noida Ward 2' },
  { area: 'Sector 7', city: 'Noida', ward: 'Noida Ward 2' },
  { area: 'Sector 8', city: 'Noida', ward: 'Noida Ward 2' },
  { area: 'Sector 9', city: 'Noida', ward: 'Noida Ward 3' },
  { area: 'Sector 10', city: 'Noida', ward: 'Noida Ward 3' },
  { area: 'Sector 11', city: 'Noida', ward: 'Noida Ward 3' },
  { area: 'Sector 12', city: 'Noida', ward: 'Noida Ward 3' },
  { area: 'Sector 14', city: 'Noida', ward: 'Noida Ward 4' },
  { area: 'Sector 15', city: 'Noida', ward: 'Noida Ward 4' },
  { area: 'Sector 15A', city: 'Noida', ward: 'Noida Ward 4' },
  { area: 'Sector 16', city: 'Noida', ward: 'Noida Ward 4' },
  { area: 'Sector 17', city: 'Noida', ward: 'Noida Ward 5' },
  { area: 'Sector 18', city: 'Noida', ward: 'Noida Ward 5' },
  { area: 'Sector 19', city: 'Noida', ward: 'Noida Ward 5' },
  { area: 'Sector 20', city: 'Noida', ward: 'Noida Ward 5' },
  { area: 'Sector 21', city: 'Noida', ward: 'Noida Ward 6' },
  { area: 'Sector 22', city: 'Noida', ward: 'Noida Ward 6' },
  { area: 'Sector 23', city: 'Noida', ward: 'Noida Ward 6' },
  { area: 'Sector 24', city: 'Noida', ward: 'Noida Ward 6' },
  { area: 'Sector 25', city: 'Noida', ward: 'Noida Ward 7' },
  { area: 'Sector 26', city: 'Noida', ward: 'Noida Ward 7' },
  { area: 'Sector 27', city: 'Noida', ward: 'Noida Ward 7' },
  { area: 'Sector 28', city: 'Noida', ward: 'Noida Ward 7' },
  { area: 'Sector 29', city: 'Noida', ward: 'Noida Ward 8' },
  { area: 'Sector 30', city: 'Noida', ward: 'Noida Ward 8' },
  { area: 'Sector 31', city: 'Noida', ward: 'Noida Ward 8' },
  { area: 'Sector 32', city: 'Noida', ward: 'Noida Ward 8' },
  { area: 'Sector 33', city: 'Noida', ward: 'Noida Ward 9' },
  { area: 'Sector 34', city: 'Noida', ward: 'Noida Ward 9' },
  { area: 'Sector 35', city: 'Noida', ward: 'Noida Ward 9' },
  { area: 'Sector 36', city: 'Noida', ward: 'Noida Ward 9' },
  { area: 'Sector 37', city: 'Noida', ward: 'Noida Ward 10' },
  { area: 'Sector 38', city: 'Noida', ward: 'Noida Ward 10' },
  { area: 'Sector 39', city: 'Noida', ward: 'Noida Ward 10' },
  { area: 'Sector 40', city: 'Noida', ward: 'Noida Ward 10' },
  { area: 'Sector 41', city: 'Noida', ward: 'Noida Ward 11' },
  { area: 'Sector 42', city: 'Noida', ward: 'Noida Ward 11' },
  { area: 'Sector 43', city: 'Noida', ward: 'Noida Ward 11' },
  { area: 'Sector 44', city: 'Noida', ward: 'Noida Ward 11' },
  { area: 'Sector 45', city: 'Noida', ward: 'Noida Ward 12' },
  { area: 'Sector 46', city: 'Noida', ward: 'Noida Ward 12' },
  { area: 'Sector 47', city: 'Noida', ward: 'Noida Ward 12' },
  { area: 'Sector 48', city: 'Noida', ward: 'Noida Ward 12' },
  { area: 'Sector 49', city: 'Noida', ward: 'Noida Ward 13' },
  { area: 'Sector 50', city: 'Noida', ward: 'Noida Ward 13' },
  { area: 'Sector 51', city: 'Noida', ward: 'Noida Ward 13' },
  { area: 'Sector 52', city: 'Noida', ward: 'Noida Ward 13' },
  { area: 'Sector 53', city: 'Noida', ward: 'Noida Ward 14' },
  { area: 'Sector 54', city: 'Noida', ward: 'Noida Ward 14' },
  { area: 'Sector 55', city: 'Noida', ward: 'Noida Ward 14' },
  { area: 'Sector 56', city: 'Noida', ward: 'Noida Ward 14' },
  { area: 'Sector 57', city: 'Noida', ward: 'Noida Ward 15' },
  { area: 'Sector 58', city: 'Noida', ward: 'Noida Ward 15' },
  { area: 'Sector 59', city: 'Noida', ward: 'Noida Ward 15' },
  { area: 'Sector 60', city: 'Noida', ward: 'Noida Ward 15' },
  { area: 'Sector 61', city: 'Noida', ward: 'Noida Ward 16' },
  { area: 'Sector 62', city: 'Noida', ward: 'Noida Ward 16' },
  { area: 'Sector 63', city: 'Noida', ward: 'Noida Ward 16' },
  { area: 'Sector 63A', city: 'Noida', ward: 'Noida Ward 16' },
  { area: 'Sector 64', city: 'Noida', ward: 'Noida Ward 17' },
  { area: 'Sector 65', city: 'Noida', ward: 'Noida Ward 17' },
  { area: 'Sector 66', city: 'Noida', ward: 'Noida Ward 17' },
  { area: 'Sector 67', city: 'Noida', ward: 'Noida Ward 17' },
  { area: 'Sector 68', city: 'Noida', ward: 'Noida Ward 18' },
  { area: 'Sector 69', city: 'Noida', ward: 'Noida Ward 18' },
  { area: 'Sector 70', city: 'Noida', ward: 'Noida Ward 18' },
  { area: 'Sector 71', city: 'Noida', ward: 'Noida Ward 18' },
  { area: 'Sector 72', city: 'Noida', ward: 'Noida Ward 19' },
  { area: 'Sector 73', city: 'Noida', ward: 'Noida Ward 19' },
  { area: 'Sector 74', city: 'Noida', ward: 'Noida Ward 19' },
  { area: 'Sector 75', city: 'Noida', ward: 'Noida Ward 19' },
  { area: 'Sector 76', city: 'Noida', ward: 'Noida Ward 20' },
  { area: 'Sector 77', city: 'Noida', ward: 'Noida Ward 20' },
  { area: 'Sector 78', city: 'Noida', ward: 'Noida Ward 20' },
  { area: 'Sector 79', city: 'Noida', ward: 'Noida Ward 20' },
  { area: 'Sector 100', city: 'Noida', ward: 'Noida Ward 21' },
  { area: 'Sector 101', city: 'Noida', ward: 'Noida Ward 21' },
  { area: 'Sector 102', city: 'Noida', ward: 'Noida Ward 21' },
  { area: 'Sector 104', city: 'Noida', ward: 'Noida Ward 22' },
  { area: 'Sector 105', city: 'Noida', ward: 'Noida Ward 22' },
  { area: 'Sector 107', city: 'Noida', ward: 'Noida Ward 22' },
  { area: 'Sector 108', city: 'Noida', ward: 'Noida Ward 23' },
  { area: 'Sector 110', city: 'Noida', ward: 'Noida Ward 23' },
  { area: 'Sector 113', city: 'Noida', ward: 'Noida Ward 23' },
  { area: 'Sector 115', city: 'Noida', ward: 'Noida Ward 24' },
  { area: 'Sector 116', city: 'Noida', ward: 'Noida Ward 24' },
  { area: 'Sector 117', city: 'Noida', ward: 'Noida Ward 24' },
  { area: 'Sector 119', city: 'Noida', ward: 'Noida Ward 24' },
  { area: 'Sector 120', city: 'Noida', ward: 'Noida Ward 25' },
  { area: 'Sector 121', city: 'Noida', ward: 'Noida Ward 25' },
  { area: 'Sector 122', city: 'Noida', ward: 'Noida Ward 25' },
  { area: 'Sector 123', city: 'Noida', ward: 'Noida Ward 25' },
  { area: 'Sector 125', city: 'Noida', ward: 'Noida Ward 26' },
  { area: 'Sector 126', city: 'Noida', ward: 'Noida Ward 26' },
  { area: 'Sector 127', city: 'Noida', ward: 'Noida Ward 26' },
  { area: 'Sector 128', city: 'Noida', ward: 'Noida Ward 26' },
  { area: 'Sector 129', city: 'Noida', ward: 'Noida Ward 27' },
  { area: 'Sector 130', city: 'Noida', ward: 'Noida Ward 27' },
  { area: 'Sector 131', city: 'Noida', ward: 'Noida Ward 27' },
  { area: 'Sector 132', city: 'Noida', ward: 'Noida Ward 27' },
  { area: 'Sector 133', city: 'Noida', ward: 'Noida Ward 28' },
  { area: 'Sector 134', city: 'Noida', ward: 'Noida Ward 28' },
  { area: 'Sector 135', city: 'Noida', ward: 'Noida Ward 28' },
  { area: 'Sector 136', city: 'Noida', ward: 'Noida Ward 28' },
  { area: 'Sector 137', city: 'Noida', ward: 'Noida Ward 29' },
  { area: 'Sector 142', city: 'Noida', ward: 'Noida Ward 29' },
  { area: 'Sector 143', city: 'Noida', ward: 'Noida Ward 29' },
  { area: 'Sector 143B', city: 'Noida', ward: 'Noida Ward 29' },
  { area: 'Sector 144', city: 'Noida', ward: 'Noida Ward 30' },
  { area: 'Sector 145', city: 'Noida', ward: 'Noida Ward 30' },
  { area: 'Sector 150', city: 'Noida', ward: 'Noida Ward 30' },
  { area: 'Sector 151', city: 'Noida', ward: 'Noida Ward 30' },
  { area: 'Sector 152', city: 'Noida', ward: 'Noida Ward 31' },
  { area: 'Sector 153', city: 'Noida', ward: 'Noida Ward 31' },
  { area: 'Sector 155', city: 'Noida', ward: 'Noida Ward 31' },
  { area: 'Sector 156', city: 'Noida', ward: 'Noida Ward 31' },
  { area: 'Sector 157', city: 'Noida', ward: 'Noida Ward 32' },
  { area: 'Sector 158', city: 'Noida', ward: 'Noida Ward 32' },
  { area: 'Sector 159', city: 'Noida', ward: 'Noida Ward 32' },
  { area: 'Sector 160', city: 'Noida', ward: 'Noida Ward 32' },
  { area: 'Sector 161', city: 'Noida', ward: 'Noida Ward 33' },
  { area: 'Sector 162', city: 'Noida', ward: 'Noida Ward 33' },
  { area: 'Sector 163', city: 'Noida', ward: 'Noida Ward 33' },
  { area: 'Sector 164', city: 'Noida', ward: 'Noida Ward 33' },
  { area: 'Sector 165', city: 'Noida', ward: 'Noida Ward 34' },
  { area: 'Sector 166', city: 'Noida', ward: 'Noida Ward 34' },
  { area: 'Sector 167', city: 'Noida', ward: 'Noida Ward 34' },
  { area: 'Sector 168', city: 'Noida', ward: 'Noida Ward 34' },
  // Noida - Notable Areas
  { area: 'Noida City Centre', city: 'Noida', ward: 'Noida Ward 5' },
  { area: 'Botanical Garden', city: 'Noida', ward: 'Noida Ward 6' },
  { area: 'Electronic City', city: 'Noida', ward: 'Noida Ward 16' },
  { area: 'Film City', city: 'Noida', ward: 'Noida Ward 17' },
  { area: 'Noida Extension (Greater Noida West)', city: 'Noida', ward: 'Noida Ward 35' },
  { area: 'Atta Market', city: 'Noida', ward: 'Noida Ward 5' },
  { area: 'DLF Mall of India Area', city: 'Noida', ward: 'Noida Ward 18' },
  { area: 'Amity University Area', city: 'Noida', ward: 'Noida Ward 26' },
];

export const CITY_OPTIONS = ['All', 'Delhi', 'Noida', 'Ghaziabad'];
